### ISSUE TITLE
Kickass background?

### ISSUE THREAD

**Issue by daantimmer** [juanmnl/vs-1984#1]
Hi,

Love the theme so far. Only 'issue' that I have is I would love to know where you've got the background in the screenshots from?

**Comment by juanmnl** [comment]
@daantimmer Glad you like it. Here's a link to the [Desktop Wallpaper](https://wallpapersite.com/creative-graphics/neon-synthwave-retrowave-grid-mountains-purple-hd-14398.html)

🚀
