### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by potatoqualitee** [juanmnl/vs-1984#15]
Just wanted to send a quick note that I 💜 1984 Unbolded and used it as a base for a Windows Terminal Theme.

I wrote about tit here: https://blog.netnerds.net/2020/07/my-windows-terminal-retro-theme/

Look how gorgeous!

![image](https://user-images.githubusercontent.com/8278033/88420655-832b1680-cde7-11ea-8cc1-21ae4d272423.png)

![image](https://user-images.githubusercontent.com/8278033/88420694-91793280-cde7-11ea-8ebf-c0854325e645.png)

Thank you for your awesome taste.

**Comment by juanmnl** [comment]
@potatoqualitee Hey! Sorry I missed this message. Thanks so much, appreciate a lot your words and that it made you feel inspired to do this. I love it!

I'll link this to the community resources on the readme if you don't mind.

tx again! :D
