### ISSUE TITLE
Add License?

### ISSUE THREAD

**Issue by JonBunator** [juanmnl/vs-1984#16]
Hey @juanmnl 
I really like your themes. Looks great!
I would love to create a theme for GitKraken with the same colors. See https://github.com/JonBunator/gitkraken-custom-themes
Can I please use your colors for that? Or can you add a license? Thank you very much :)

**Comment by juanmnl** [comment]
Hey @JonBunator 
Thanks for your message.
Please feel free to use whichever colors that you'd like, and, if possible, do a PR including a link to gitkraken theme to the readme whenever you have it. (Not sure which license I should use for this, any recommendation?)

**Comment by JonBunator** [comment]
Thanks for the quick reply and the permission to use your colors!

>  if possible, do a PR including a link to gitkraken theme to the readme whenever you have it.

I'll do that

> (Not sure which license I should use for this, any recommendation?)

For me, a license is not really necessary since you gave me the permission to use your colors. But it makes it easier for others to use your code. I'll suggest you read up on the different licenses (https://snyk.io/learn/open-source-licenses/). It all depends on how much freedom you want to give the user. MIT is very popular for example because it's short and easy to understand.
