### ISSUE TITLE
Title Bar text color aggressively pink

### ISSUE THREAD

**Issue by Inclushe** [juanmnl/vs-1984#2]
First impressions are pretty killer.
IMO, the title bar text color is too pink. I think sticking with white would be better.
![image](https://user-images.githubusercontent.com/7546357/58045081-74741000-7b0f-11e9-8c31-a2792acb55d8.png)

**Comment by juanmnl** [comment]
@Inclushe Hey! sorry about that and thanks for the heads-up. Will be fixed on the next patch. :D

**Comment by juanmnl** [comment]
@Inclushe Should be better on 0.0.7 (update should be available soon)

**Comment by juanmnl** [comment]
@Inclushe Was this Issue solved? I'm sure there's a better color for that but I don't have any other OS than macOS to test and it seems to be a OS specific issue. Hope I was able to override it. LMK! 😄

**Comment by Inclushe** [comment]
Yep, that fixed it. 
![image](https://user-images.githubusercontent.com/7546357/58056961-1bb56f00-7b31-11e9-9878-30663c1ff4ae.png)
