### ISSUE TITLE
iTerm 2 Color Scheme

### ISSUE THREAD

**Issue by covertbert** [juanmnl/vs-1984#3]
I've made an iTerm 2 theme to match your VSCode theme because I know a lot of people (myself included) like to have them matching. Totally up to you but I figured you could add a link to it if you like https://github.com/covertbert/iTerm2-color-schemes/blob/master/1984.itermcolors

**Comment by juanmnl** [comment]
@covertbert That's awesome!! Will link it on the readme and tag you there (do you have a twitter account to add it too?) :D Thanks!

**Comment by covertbert** [comment]
@juanmnl Thanks man, much appreciated! I'm afraid I don't use Twitter but thanks anyway :)
