### ISSUE TITLE
invisible list item selection

### ISSUE THREAD

**Issue by kinghat** [juanmnl/vs-1984#4]
impossible to see the list item that is selected in orwellian:

![image](https://user-images.githubusercontent.com/16073360/58500667-39de2900-8148-11e9-9826-0d82e2ecee2a.png)

**Comment by juanmnl** [comment]
@k1nghat Thanks for the heads-up! will fix on the next release :)

**Comment by juanmnl** [comment]
@k1nghat Should be fixed on 0.0.27. Let me know if it works so I can close this one 😄

**Comment by kinghat** [comment]
works well. tyvm
