### ISSUE TITLE
iTerm 2 themes again (sorry)

### ISSUE THREAD

**Issue by covertbert** [juanmnl/vs-1984#6]
Just to mention I've added a light version for iTerm and I'm also going to add one for the Orwellian theme. I've also renamed the repo to just be "1984" themes so maybe it would make sense for you to link to the [root of the repo instead](https://github.com/covertbert/iterm2-1984)

**Comment by juanmnl** [comment]
@covertbert Please! Don't be sorry. I'm really grateful for this contribution and I'll update the readme link later today. 😄 Thanks again!

**Comment by covertbert** [comment]
Thanks :)
