### ISSUE TITLE
Hard to read IntelliSense text on the Orwellian theme

### ISSUE THREAD

**Issue by AlexAegis** [juanmnl/vs-1984#7]
Using the Orwellian theme, the background of the IntelliSense box is too transparent and the text on it and behind are too similar in brightness, making it hard to read.

Consider making the IntelliSense box opaque.

## Filename and Language selected

*.rs, Rust

## VSCode theme Screenshot

![image](https://user-images.githubusercontent.com/16900547/58741116-fc162480-8415-11e9-9309-c0f7fd77a160.png)

## Versions used

* VSCode version: 1.34.0
* Theme version: 0.0.29

**Comment by juanmnl** [comment]
@AlexAegis Thanks for your feedback. Gonna fix it asap and push it on the next release. I'll notify you.

Thanks again :)

**Comment by juanmnl** [comment]
@AlexAegis Should be fixed on 0.0.30, let me know so I can close this issue.
Tx again for the feedback 🚀

**Comment by AlexAegis** [comment]
Yes. Also, the dark background fits well. Thanks.
