### ISSUE TITLE
Minor color changes to 1984 theme

### ISSUE THREAD

**Issue by johnnyhuy** [juanmnl/vs-1984#8]
First I gotta say, fantastic color theme you've made 👌

However there seems to be a few odd colors and I'm wondering if this was intended?

- Gray color background on the file item buttons
- Gray color on commit message box
- Default bright blue color on the new VSCode Remote extension button at the bottom left corner (all default themes have the ability to change the color suited its theme)

## VSCode theme Screenshot

![image](https://user-images.githubusercontent.com/27847622/59760576-f9e90c80-92d5-11e9-8707-ba40dbb95d61.png)

## Versions used

* VSCode version: 1.35
* Theme version: 0.0.30

On Windows 1809 build.

**Comment by mittalyashu** [comment]
Yes, there is a gray color on the status bar too, when you do not open vs code in any folder.

![J22NgSnMPX](https://user-images.githubusercontent.com/29014463/59974145-20ed5a00-95c6-11e9-889c-02226829dd3e.png)

**Comment by juanmnl** [comment]
@johnnyhuy @mittalyashu Thanks for the feedback, appreciate it :D I'll take care of this on the next version, maybe on the weekend. Will tag you when it's up so you can test it. Thanks again!

**Comment by juanmnl** [comment]
@johnnyhuy @mittalyashu These should be fixed in 0.0.35. Sorry for taking so long and thanks again for the feedback.
