### ISSUE TITLE
Context menu with transparency

### ISSUE THREAD

**Issue by Audomaro** [juanmnl/vs-1984#9]
It's a great vscode theme 💯 👍 . It only has one detail with the ligth version, the contextual menu appears transparent.

![image](https://user-images.githubusercontent.com/6589247/60618809-c9f13d00-9d9c-11e9-8703-64ba75882388.png)

**Comment by juanmnl** [comment]
@Audomaro thanks for the feedback, will try to fix it as soon as possible. Will ping you when the fix is up. :D

**Comment by juanmnl** [comment]
@Audomaro Hey, so sorry for coming back to this after so much time, been trying to find where this problem could originate, without success.
Could you verify if this ain't something coming from the system as I don't have any transparency set but for highlighted text.

I'm on a mac and wasn't able to replicate the issue, sorry about that.
